language: julia

os:
  - linux

julia:
  - release

before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'include("make.jl")'
