site_name:        JuliaSmoothOptimizers
repo_url:         https://github.com/JuliaSmoothOptimizers
site_description: Julia Smooth Optimizers organization. Models, solvers, and CUTEst access.
site_author:      JuliaSmoothOptimizers

theme: material

extra:
  palette:
    primary: 'deep orange'
    accent: 'indigo'
  author:
    github: JuliaSmoothOptimizers

markdown_extensions:
  - extra
  - tables
  - codehilite(css_class=code, guess_lang=False)
  - fenced_code

docs_dir: src

pages:
  - Home: index.md
  - Status: status.md
